'use client'

import '@/styles/docs.css'
import Header from '@/components/Header'
import Link from 'next/link'
import { useCallback, useLayoutEffect, useState } from 'react'
import { isStaticBuild } from '@/utils/build'
import {
  FileCode, 
  Zap, 
  Book, 
  Wrench,
  HelpCircle,
  ArrowRight,
  Terminal,
  Package,
  Volume2,
  CheckCircle,
  Copy,
  Check
} from 'lucide-react'

const quickStartContent = isStaticBuild ? `# Quick Start

Peal will be available soon! We're putting the finishing touches on our sound library.

## What's Coming

1. **Professional UI Sounds** - Carefully crafted sounds for modern web apps
2. **Easy Integration** - Simple API that works with any framework  
3. **Lightweight** - Tiny footprint, big impact

Stay tuned for the official launch!` : `# Quick Start

Get Peal sounds working in your app in under 2 minutes.

## 1. Add Sounds (30 seconds)

\`\`\`bash
npx @peal-sounds/peal add click success error notification
\`\`\`

This downloads professional UI sounds and generates a helper file.

## 2. Install the Library (30 seconds)

\`\`\`bash
npm install @peal-sounds/peal
\`\`\``

const sections = [
  {
    id: 'quick-start',
    title: 'Quick Start',
    icon: Zap,
    content: quickStartContent + `

## 3. Use It (1 minute)

\`\`\`javascript
import { peal } from './peal';

// In your click handler
button.addEventListener('click', async () => {
  peal.click();  // Play click sound
  
  try {
    await saveData();
    peal.success();  // Play success sound
  } catch (err) {
    peal.error();    // Play error sound
  }
});
\`\`\`

That's it! You now have professional UI sounds in your app.
    `
  },
  {
    id: 'api',
    title: 'API Reference',
    icon: FileCode,
    content: `
# API Reference

## Basic Usage

\`\`\`javascript
import { peal } from './peal';  // Generated by CLI

peal.click();      // Play click sound
peal.success();    // Play success sound
\`\`\`

## Methods

### Playing Sounds

#### \`peal.play(soundName, options?)\`
Play any sound with optional settings.

\`\`\`javascript
peal.play('success', {
  volume: 0.5,    // Volume (0-1)
  loop: false,    // Loop the sound
  rate: 1.0       // Playback speed
});
\`\`\`

#### Convenience Methods
Each sound added via CLI gets its own method:

\`\`\`javascript
peal.click()       // Same as peal.play('click')
peal.success()     // Same as peal.play('success')
peal.error()       // Same as peal.play('error')
\`\`\`

### Playback Control

#### \`peal.stop(soundName?)\`
Stop sounds immediately.

\`\`\`javascript
peal.stop('success');  // Stop specific sound
peal.stop();          // Stop all sounds
\`\`\`

#### \`peal.pause(soundName?)\`
Pause sounds (resumable).

\`\`\`javascript
peal.pause('music');   // Pause specific sound
peal.pause();         // Pause all sounds
\`\`\`

### Volume Control

#### \`peal.volume(level?)\`
Global volume control.

\`\`\`javascript
peal.volume(0.5);           // Set to 50%
const current = peal.volume(); // Get current volume
\`\`\`

#### \`peal.mute(muted?)\`
Global mute control.

\`\`\`javascript
peal.mute(true);            // Mute all sounds
peal.mute(false);           // Unmute
const isMuted = peal.mute(); // Get mute state
\`\`\`
    `
  },
  {
    id: 'cli',
    title: 'CLI Commands',
    icon: Terminal,
    content: `
# CLI Commands

## List All Sounds
\`\`\`bash
npx @peal-sounds/peal list
\`\`\`

## Add Sounds
\`\`\`bash
# Interactive selection
npx @peal-sounds/peal add

# Add specific sounds
npx @peal-sounds/peal add click success error

# Add to custom directory
npx @peal-sounds/peal add --dir ./sounds

# Generate TypeScript helper
npx @peal-sounds/peal add --typescript
\`\`\`

## Remove Sounds
\`\`\`bash
# Interactive removal
npx @peal-sounds/peal remove

# Remove specific sounds
npx @peal-sounds/peal remove click tap

# Remove from custom directory
npx @peal-sounds/peal remove --dir ./sounds
\`\`\`

## Play Sounds
\`\`\`bash
# Play a specific sound
npx @peal-sounds/peal play click

# Play a demo of all sounds
npx @peal-sounds/peal demo

# Demo with custom delay
npx @peal-sounds/peal demo --delay 2000
\`\`\`
    `
  },
  {
    id: 'examples',
    title: 'Examples',
    icon: Book,
    content: `
# Framework Examples

## React

\`\`\`jsx
import { peal } from './peal';
import { useState } from 'react';

function SubmitButton({ onSubmit }) {
  const [isLoading, setIsLoading] = useState(false);

  const handleClick = async () => {
    peal.click();
    setIsLoading(true);
    
    try {
      await onSubmit();
      peal.success();
    } catch (error) {
      peal.error();
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <button 
      onClick={handleClick}
      onMouseEnter={() => peal.hover()}
      disabled={isLoading}
    >
      {isLoading ? 'Submitting...' : 'Submit'}
    </button>
  );
}
\`\`\`

## Vue 3

\`\`\`vue
<template>
  <button 
    @click="handleSubmit" 
    @mouseenter="peal.hover()"
    :disabled="isLoading"
  >
    {{ isLoading ? 'Submitting...' : 'Submit' }}
  </button>
</template>

<script setup>
import { ref } from 'vue';
import { peal } from './peal';

const isLoading = ref(false);

const handleSubmit = async () => {
  peal.click();
  isLoading.value = true;
  
  try {
    await submitForm();
    peal.success();
  } catch (error) {
    peal.error();
  } finally {
    isLoading.value = false;
  }
};
</script>
\`\`\`

## Common Patterns

### Loading States
\`\`\`javascript
async function fetchData() {
  peal.play('loading', { loop: true });
  
  try {
    const data = await api.getData();
    peal.stop('loading');
    peal.complete();
    return data;
  } catch (err) {
    peal.stop('loading');
    peal.error();
    throw err;
  }
}
\`\`\`

### Form Validation
\`\`\`javascript
async function submitForm(data) {
  peal.click();
  
  try {
    await api.submit(data);
    peal.success();
    showNotification('Saved!');
  } catch (error) {
    peal.error();
    showNotification('Failed to save');
  }
}
\`\`\`
    `
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    icon: HelpCircle,
    content: `
# Troubleshooting

## Sounds Not Playing

### Browser Console Errors
\`\`\`
DOMException: play() failed because the user didn't interact with the document first
\`\`\`

**Solution**: Sounds must be triggered by user interaction.

\`\`\`javascript
// ❌ Won't work - no user interaction
window.onload = () => peal.startup();

// ✅ Works - user clicked
button.onclick = () => peal.startup();
\`\`\`

### Module Import Errors

\`\`\`javascript
// ES Modules (most modern projects)
import { peal } from './peal';

// CommonJS (older Node.js projects)
const { peal } = require('./peal');
\`\`\`

### Build/Bundle Issues

**Vite** - Copy sounds to public:
\`\`\`javascript
// vite.config.js
export default {
  publicDir: 'public',
  // Sounds in public/peal/ will be served at /peal/
}
\`\`\`

**Next.js** - Put in public folder:
\`\`\`bash
# Move sounds to public
mv peal public/

# Update peal.js to use public path
peal.load('click', '/peal/click.wav');
\`\`\`

## Debug Checklist

1. **Open browser console** - Any errors?
2. **Check network tab** - Are WAV files loading?
3. **Verify file paths** - Do paths in peal.js match file locations?
4. **Test with demo** - Does \`npx @peal-sounds/peal demo\` work?
5. **Check volume/mute** - System volume, browser tab not muted?
6. **User interaction** - Sounds triggered by user action?
    `
  }
]

function CodeBlock({ children, language = 'javascript' }: { children: string, language?: string }) {
  const [copied, setCopied] = useState(false)
  const isTerminal = language === 'bash' || language === 'shell'

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(children)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy text: ', err)
    }
  }

  if (isTerminal) {
    const lines = children.split('\n')

    // Multi-line scripts (with comments / blank separators) need a real
    // pre-formatted well — the single-line pill collapses newlines.
    if (lines.length > 1) {
      return (
        <div className="docs-code-block docs-terminal-block">
          <button
            type="button"
            onClick={copyToClipboard}
            className="docs-copy-btn"
            title="Copy to clipboard"
            aria-label="Copy command"
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
          </button>
          <pre>
            {lines.map((line, idx) => (
              <span key={idx}>
                {/^\s*#/.test(line) ? (
                  <span className="docs-term-cmt">{line}</span>
                ) : line.length > 0 ? (
                  <>
                    <span className="docs-term-prompt">$</span>
                    {line}
                  </>
                ) : null}
                {'\n'}
              </span>
            ))}
          </pre>
        </div>
      )
    }

    return (
      <div className="docs-terminal-cmd">
        <code>
          <span className="prompt">$</span>
          {children}
        </code>
        <button
          type="button"
          onClick={copyToClipboard}
          className="docs-copy-btn"
          title="Copy to clipboard"
          aria-label="Copy command"
        >
          {copied ? <Check size={14} /> : <Copy size={14} />}
        </button>
      </div>
    )
  }

  return (
    <div className="docs-code-block">
      <button
        type="button"
        onClick={copyToClipboard}
        className="docs-copy-btn"
        title="Copy to clipboard"
        aria-label="Copy code"
      >
        {copied ? <Check size={14} /> : <Copy size={14} />}
      </button>
      <pre>
        <code>{children}</code>
      </pre>
    </div>
  )
}

function renderInline(text: string, keyPrefix: string): React.ReactNode[] {
  const nodes: React.ReactNode[] = []
  const boldParts = text.split(/\*\*/)

  boldParts.forEach((part, bi) => {
    if (!part) return
    if (bi % 2 === 1) {
      nodes.push(<strong key={`${keyPrefix}-b-${bi}`}>{part}</strong>)
      return
    }
    const codeParts = part.split('`')
    codeParts.forEach((cp, ci) => {
      if (!cp) return
      if (ci % 2 === 1) {
        nodes.push(<code key={`${keyPrefix}-c-${bi}-${ci}`}>{cp}</code>)
      } else {
        nodes.push(cp)
      }
    })
  })

  return nodes
}

function MarkdownContent({ content, skipTitle }: { content: string; skipTitle?: boolean }) {
  const lines = content.trim().split('\n')
  const elements: React.ReactNode[] = []
  let i = 0
  let skippedTitle = !skipTitle

  while (i < lines.length) {
    const line = lines[i]

    if (line.startsWith('# ')) {
      if (!skippedTitle) {
        skippedTitle = true
        i++
        continue
      }
      elements.push(<h1 key={i}>{line.substring(2)}</h1>)
    } else if (line.startsWith('## ')) {
      elements.push(<h2 key={i}>{line.substring(3)}</h2>)
    } else if (line.startsWith('### ')) {
      elements.push(<h3 key={i}>{line.substring(4)}</h3>)
    } else if (line.startsWith('#### `') && line.endsWith('`')) {
      const signature = line.slice(5, -1)
      let description = ''
      if (i + 1 < lines.length && lines[i + 1].trim() && !lines[i + 1].startsWith('#') && !lines[i + 1].startsWith('```')) {
        description = lines[i + 1].trim()
        i++
      }
      elements.push(
        <div key={i} className="docs-method">
          <p className="docs-method-sig">{signature}</p>
          {description ? <p className="docs-method-desc">{description}</p> : null}
        </div>
      )
    } else if (line.startsWith('#### ')) {
      elements.push(<h4 key={i}>{line.substring(5)}</h4>)
    }
    // Code blocks
    else if (line.startsWith('```')) {
      const language = line.substring(3)
      const codeLines = []
      i++
      while (i < lines.length && !lines[i].startsWith('```')) {
        codeLines.push(lines[i])
        i++
      }
      elements.push(
        <CodeBlock key={`code-${i}`} language={language}>
          {codeLines.join('\n')}
        </CodeBlock>
      )
    }
    else if (/^\d+\.\s/.test(line)) {
      const items: React.ReactNode[] = []
      const start = i
      while (i < lines.length && /^\d+\.\s/.test(lines[i])) {
        const itemText = lines[i].replace(/^\d+\.\s/, '')
        items.push(<li key={i}>{renderInline(itemText, `li-${i}`)}</li>)
        i++
      }
      elements.push(<ol key={`ol-${start}`}>{items}</ol>)
      continue
    }
    else if (line.includes('`') || line.includes('**')) {
      elements.push(<p key={i}>{renderInline(line, `p-${i}`)}</p>)
    }
    // Regular paragraphs
    else if (line.trim()) {
      elements.push(<p key={i}>{line}</p>)
    }
    
    i++
  }
  
  return <div className="docs-prose">{elements}</div>
}

const sectionKickers: Record<string, string> = {
  'quick-start': 'Guide',
  api: 'API',
  cli: 'CLI',
  examples: 'Examples',
  troubleshooting: 'Help',
}

const sectionLeads: Record<string, string> = {
  'quick-start': 'Get Peal sounds working in your app in under 2 minutes.',
  api: 'Play, stop, and control volume on the CLI-generated helper module.',
  cli: 'Add, remove, and preview sounds from the terminal.',
  examples: 'Drop-in patterns for React, Vue, and vanilla JavaScript.',
  troubleshooting: 'Common issues and how to fix them.',
}

export default function DocsPage() {
  const [activeSection, setActiveSection] = useState('quick-start')
  const activeContent = sections.find(s => s.id === activeSection)
  const isOverview = activeSection === 'quick-start'
  const ActiveIcon = activeContent?.icon

  const selectSection = useCallback((id: string) => {
    setActiveSection(id)
  }, [])

  useLayoutEffect(() => {
    window.scrollTo(0, 0)
  }, [activeSection])

  return (
    <div className="docs">
      <Header />
      <main className="docs-shell">
        <div className="docs-layout">
          <nav className="docs-sidebar" aria-label="Documentation sections">
            <div className="docs-sidebar-panel">
              <div className="docs-sidebar-label">Sections</div>
              {sections.map((section) => {
                const Icon = section.icon
                return (
                  <button
                    key={section.id}
                    type="button"
                    onClick={() => selectSection(section.id)}
                    className={`docs-sidebar-link${activeSection === section.id ? ' is-active' : ''}`}
                  >
                    <Icon size={15} />
                    {section.title}
                  </button>
                )
              })}
            </div>
          </nav>

          <div className="docs-main">
            <div className="docs-page-header">
              {isOverview ? (
                <div className="docs-hero">
                  <div className="docs-kicker">Developer docs</div>
                  <h1>Documentation</h1>
                  <p>Everything you need to add professional sounds to your web app</p>
                </div>
              ) : activeContent ? (
                <header className="docs-article-header">
                  <div className="docs-kicker">{sectionKickers[activeContent.id] ?? 'Docs'}</div>
                  <div className="docs-article-title">
                    {ActiveIcon ? <ActiveIcon size={22} className="docs-article-icon" /> : null}
                    <h1>{activeContent.title}</h1>
                  </div>
                  <p className="docs-article-lead">{sectionLeads[activeContent.id]}</p>
                </header>
              ) : null}
            </div>

            <div className="docs-content-panel">
              {activeContent && (
                <MarkdownContent content={activeContent.content} skipTitle />
              )}
            </div>

            {isOverview && !isStaticBuild && (
              <div className="docs-quick-links">
                <Link
                  href="https://www.npmjs.com/package/@peal-sounds/peal"
                  target="_blank"
                  className="docs-quick-link"
                >
                  <Package className="docs-quick-icon" />
                  <h3>npm Package</h3>
                  <p>@peal-sounds/peal</p>
                  <ArrowRight className="docs-quick-arrow" />
                </Link>

                <Link
                  href="https://github.com/arach/peal"
                  target="_blank"
                  className="docs-quick-link"
                >
                  <FileCode className="docs-quick-icon" />
                  <h3>GitHub</h3>
                  <p>Source code &amp; issues</p>
                  <ArrowRight className="docs-quick-arrow" />
                </Link>

                <button
                  type="button"
                  onClick={() => selectSection('quick-start')}
                  className="docs-quick-link"
                >
                  <Zap className="docs-quick-icon" />
                  <h3>Quick Start</h3>
                  <p>Get started in 2 minutes</p>
                  <ArrowRight className="docs-quick-arrow" />
                </button>
              </div>
            )}

            {activeSection === 'quick-start' && (
              <div className="docs-features">
                <div className="docs-feature">
                  <Terminal />
                  <h3>CLI Manages Sounds</h3>
                  <p>Add and remove sounds from our curated collection with simple commands</p>
                </div>
                <div className="docs-feature">
                  <Volume2 />
                  <h3>Library Plays Them</h3>
                  <p>Thin wrapper around Howler.js with zero configuration needed</p>
                </div>
                <div className="docs-feature">
                  <CheckCircle />
                  <h3>TypeScript Ready</h3>
                  <p>Full TypeScript support with generated types for your sounds</p>
                </div>
                <div className="docs-feature">
                  <Wrench />
                  <h3>Framework Agnostic</h3>
                  <p>Works with React, Vue, Svelte, or vanilla JavaScript</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  )
}